version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nextjs_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      NODE_ENV: production
    ports:
      - "80:3000"
    depends_on:
      - db

volumes:
  postgres_data:
